## get rooms

GET http://localhost:0216/rooms

###

## get one room
GET http://localhost:0216/rooms/ed24ec95-f0ad-4fd5-ae51-d38a6c40d37f

###
POST http://localhost:0216/rooms
Content-Type: application/json

{
        "name": "Conference-Room-12",
        "capacity": 43,
        "type": "Conference"   
}

###
# Update room
PUT http://localhost:0216/rooms/e333311f-105d-4fcd-b274-c00d1a033f58
Content-Type: application/json

{
        "name": "Room-2",
        "capacity": "8",
        "type": "Workspace"
}

###

##hämta alla users
GET http://localhost:0216/users

###
## update user
PUT http://localhost:0216/users/00b98b9b-99c7-4b79-8f32-855228848ae7
Content-Type: application/json

{
        "username": "Mohsen Intezar",
        "password": "mohsen123"
}